name       : sxhkd
version    : 0.6.1
release    : 5
source     :
    - https://github.com/baskerville/sxhkd/archive/0.6.1.tar.gz : 5f44d623ef6fda01062dcfe8d5d0b75efad9a38114a28983ae895dbcbf43323e
license    : BSD-2-Clause
component  : desktop
summary    : Simple X hotkey daemon
description: |
    Simple X hotkey daemon
builddeps  :
    - pkgconfig(xcb-event)
    - pkgconfig(xcb-keysyms)
rundeps    :
    - xdo
build      : |
    %make PREFIX=/usr
install    : |
    %make_install PREFIX=/usr
    install -Dm00644 contrib/systemd/sxhkd.service $installdir/%libdir%/systemd/system/sxhkd.service
