name       : sxhkd
version    : 0.5.9
release    : 4
source     :
    - https://github.com/baskerville/sxhkd/archive/0.5.9.tar.gz : 457e0fdfe0a7dac24ca506c026a1e8cde5899073ba1d2ef1326bc68b931648bd
license    : BSD-2-Clause
component  : desktop
summary    : Simple X hotkey daemon
description: |
    Simple X hotkey daemon
builddeps  :
    - pkgconfig(xcb-event)
    - pkgconfig(xcb-keysyms)
rundeps    :
    - xdo
build      : |
    %make PREFIX=/usr
install    : |
    %make_install PREFIX=/usr
    install -Dm00644 contrib/systemd/sxhkd.service $installdir/%libdir%/systemd/system/sxhkd.service
